### ISSUE TITLE
Impossible to display sampled signals Y values

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#403] opened 2024-01-25 11:39 UTC
If you check the sampled signals, the Y values are not displayed: I have found that when a signal is sampled, the cursors on the results do not show Y values.

See the below example:
<img width="934" alt="sampled" src="https://github.com/aesim-tech/simba-project/assets/115028249/1efa4a6f-6e24-4d24-af86-11fce9f5f351">

and the results:
<img width="946" alt="sampled1" src="https://github.com/aesim-tech/simba-project/assets/115028249/b1d70c45-ccb4-417b-980a-2d8746a49c1d">

**Comment by manu-aesim** [comment] 2024-01-25 16:43
Duplicate of #380

**Closed as completed by manu-aesim** 2024-01-25 16:43 UTC
Labels: duplicate
