### ISSUE TITLE
"selector" control block

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#409] opened 2024-02-12 07:59 UTC
Creation  of a "control" block to select signals.
For example: I have a control signal that I want to be able to select from two or more sources depending on a variable that could be time or a signal level.

The goal is to create a kind of "selector" block.

**Comment by manu-aesim** [comment] 2024-02-12 13:56
Duplicate of https://github.com/aesim-tech/simba-project/issues/126

**Closed as completed** 2024-02-12 13:56 UTC
Labels: duplicate
