### ISSUE TITLE
Impossible to load xml file of a mosfet_w_diode (version 1.3)

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#349] opened 2023-10-14 18:53 UTC
When I try to load an new xml file of a mosfet_w_diode (version 1.3) from Infineon, I get the following error message.

![image](https://github.com/aesim-tech/simba-project/assets/28732566/aed1a7bb-2629-4c5e-ab60-847664c582ed)

I tried with the official release and the last beta release 2023-10-13.

I cannot remember if Simba is supposed to support this last version of xml file format.
- If yes, then we can consider this is a bug.
- If no, then we could consider this as a feature request.

[IMBG120R060M1H_mosfet_w_diode.zip](https://github.com/aesim-tech/simba-project/files/12907476/IMBG120R060M1H_mosfet_w_diode.zip)

**Comment by manu-aesim** [comment] 2023-10-16 13:03
SIMBA supports the latest xml file format. This bug was caused by our XML deserialized and is now fixed.

**Closed as completed by manu-aesim** 2023-10-16 13:03 UTC
Labels: bug
