### ISSUE TITLE
Bug: multi labels connected to the same connector

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#311] opened 2023-07-20 07:05 UTC
**Describe the bug**
There is a bug when connecting one block to multiple labels
see attached the error explaining clearly the issue

** SIMBA Version**
 - Version : 23.05

The issue is solved if you connect only one block to only one label.

![error](https://github.com/aesim-tech/simba-project/assets/115028249/2bda0f3b-7580-4843-90c5-20d1c7da34c5)

**Comment by manu-aesim** [comment] 2023-07-24 08:46
Hello,

This is is not a bug but a limitation to avoid signal type conflict. I will close it for now.

**Comment by ghost** [comment] 2023-07-24 13:02
Hello,

Thanks for this answer. So it seems right now we cannot connect one block to multiple labels.
However is there a workaround to realize this ?
Or we can only use one block for one label ?

Thanks,
KR

**Comment by manu-aesim** [comment] 2023-07-24 13:13
Hi,

If it's a control signal you can add a gain of 1 and connect its output to the new label.

**Closed as completed** 2023-07-24 13:13 UTC
Labels: invalid
